config/routes.rb
Rails.application.routes.draw do
  resources :cargos
    resources :colaboradores
    root to: 'welcome#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :colaboradores

  validates :nome, presence: true, length: { maximum: 60 }
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
  belongs_to :cargo
  validates :nome, :cidade, :bairro, :endereco, presence: true,
                                                length: { maximum: 80 }
  validates :sexo, presence: true, length: { is: 1 }
  validates :estado, presence: true, length: { is: 2 }
  validates :cpf, presence: true, numericality: true, uniqueness: true,
                  length: { is: 11 }
  validates :rg, presence: true, length: { maximum: 15 }
  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      on: :create }
  validates :dt_nascimento, :dt_inicio, presence: true
  validates :numero, presence: true, length: { maximum: 20 }
  validates :cep, presence: true, length: { is: 9 }
  validates :telefone, :celular, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
require './lib/application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  protect_from_forgery with: :exception
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[show edit update destroy]

  def index
    @cargos = Cargo.all
  end

  def show; end

  def new
    @cargo = Cargo.new
  end

  def edit; end

  def create
    @cargo = Cargo.new(cargo_params)
    if @cargo.save
      respond_with @cargo
    else
      render :new
    end
  end

  def update
    @cargo = Cargo.new(cargo_params)
    if @cargo.save
      respond_with @cargo
    else
      render :new
    end
  end

  def destroy
    @cargo.destroy
    respond_with @cargo
  end

  private
  
  def set_cargo
    @cargo = Cargo.find(params[:id])
  end

  def cargo_params
    params.require(:cargo).permit(:nome, :descricao)
  end
end

app/controllers/colaboradores_controller.rb
class ColaboradoresController < ApplicationController
  before_action :set_colaborador, only: %i[show edit update destroy]
  def index
    @colaboradores = Colaborador.all
  end

  def show; end

  def new
    @colaborador = Colaborador.new
  end

  def edit; end

  def create
    @colaborador = Colaborador.new(colaborador_params)
    if @colaborador.save
      respond_with @colaborador
    else
      render :new
    end
  end

  def update
    @colaborador = Colaborador.new(colaborador_params)
    if @colaborador.save
      respond_with @colaborador
    else
      render :edit
    end
  end

  def destroy
    @colaborador.destroy
    respond_with @colaborador
  end

  private
  
  def set_colaborador
    @colaborador = Colaborador.find(params[:id])
  end

  def colaborador_params
    params.require(:colaborador).permit(:nome, :sexo, :dt_nascimento, :estado,
                                        :cpf, :rg, :numero, :compl, :cep, :foto,
                                        :cidade, :endereco, :telefone, :celular,
                                        :email, :bairro, :dt_inicio, :dt_saida,
                                        :cargo_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/colaboradores_helper.rb
module ColaboradoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cargos/_form.html.erb
<%= simple_form_for(@cargo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome, label: 'Nome:' %>
    <%= f.input :descricao, label: 'Descrição:' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: "btn btn-default btn-primary" %>
    <%= link_to 'Voltar', cargos_path, class: "btn btn-default btn-warning" %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h2>Editar Cargo</h2>

<%= render 'form', cargo: @cargo %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cargos</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.nome %></td>
        <td><%= cargo.descricao %></td>
        <td><%= link_to 'Exibir', cargo %></td>
        <td><%= link_to 'Editar', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Excluir', cargo, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="form-actions" style="color: white">
  <%= link_to 'Novo Cargo', new_cargo_path, class: "btn btn-info" %>
  <%= link_to 'Voltar', root_path, class: "btn btn-warning" %>
</div>

app/views/cargos/new.html.erb
<h1>Novo Cargo</h1>

<%= render 'form', cargo: @cargo %>

app/views/cargos/show.html.erb
<h1>Exibir Cargo</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cargo.nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @cargo.descricao %>
</p>

<%= link_to 'Editar', edit_cargo_path(@cargo) %> |
<%= link_to 'Voltar', cargos_path %>

app/views/colaboradores/_form.html.erb
<%= simple_form_for @colaborador, html:{ class: 'form-control' } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :nome, label: 'Nome:' %>
    <%= f.input :sexo, label: 'Sexo:', collection: [['Masculino', 'M'],['Feminino', 'F']], 
                       as: :radio_buttons, item_wrapper_class: 'custom-control custom-control-inline' %>
    <%= f.input :dt_nascimento, label: 'Data de Nascimento:', as: :date, html5: true %>
    <%= f.input :cpf, label: 'CPF:' %>
    <%= f.input :rg, label: 'RG:' %>
    <%= f.association :cargo, label: 'Cargo:', label_method: :nome, value_method: :id %>
    <%= f.input :endereco, label: 'Logradouro:' %>
    <%= f.input :numero, label: 'Numero:' %>
    <%= f.input :compl, label: 'Compl:' %>
    <%= f.input :cep, label: 'CEP:' %>
    <%= f.input :bairro, label: 'Bairro:' %>
    <%= f.input :cidade, label: 'Cidade:' %>
    <%= f.input :estado, label: 'Estado:' %>
    <%= f.input :telefone, label: 'Telefone:' %>
    <%= f.input :celular, label: 'Celular:' %>
    <%= f.input :email, label: 'Email:' %>
    <%= f.input :foto, label: 'Foto:', as: :file %>
    <%= f.input :dt_inicio, label: 'Data de Entrada:', as: :date, html5: true %>
    <%= f.input :dt_saida, label: 'Data de Saída:', as: :date, html5: true %>
    
  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: "btn btn-default btn-primary" %>
    <%= link_to 'Voltar', colaboradores_path, class: "btn btn-default btn-warning" %>
  </div>
<% end %>

app/views/colaboradores/edit.html.erb
<h2>Editar Colaborador</h2>

<%= render 'form', colaborador: @colaborador %>

app/views/colaboradores/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Colaboradores</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Cargo</th>
      <th scope="col">Celular</th>
      <th scope="col">Email</th>
      <th scope="col">Início</th>
      <th scope="col">Saída</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @colaboradores.each do |colaborador| %>
      <tr>
        <td><%= colaborador.nome %></td>
        <td><%= colaborador.cargo.nome %></td>
        <td><%= colaborador.celular %></td>
        <td><%= colaborador.email %></td>
        <td><%= colaborador.dt_inicio.strftime('%d/%m/%Y') %></td>
        <% if colaborador.dt_saida %>
          <td><%= colaborador.dt_saida.strftime('%d/%m/%Y') %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Exibir', colaborador %></td>
        <td><%= link_to 'Editar', edit_colaborador_path(colaborador) %></td>
        <td><%= link_to 'Excluir', colaborador, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="form-actions" style="color: white">
  <%= link_to 'Novo Colaborador', new_colaborador_path, class: "btn btn-info" %>
  <%= link_to 'Voltar', root_path, class: "btn btn-warning" %>
</div>

app/views/colaboradores/new.html.erb
<h1>Novo Colaborador</h1>
<div class="row">
  <%= render 'form', colaborador: @colaborador %>


</div>

app/views/colaboradores/show.html.erb
<h2>Exibir Colaborador</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @colaborador.nome %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @colaborador.sexo %>
</p>

<p>
  <strong>Data de Nascimento:</strong>
  <%= @colaborador.dt_nascimento.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @colaborador.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @colaborador.rg %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @colaborador.cargo.nome %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @colaborador.endereco %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @colaborador.numero %>
</p>

<p>
  <strong>Compl:</strong>
  <%= @colaborador.compl %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @colaborador.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @colaborador.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @colaborador.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @colaborador.estado %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @colaborador.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @colaborador.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @colaborador.email %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @colaborador.foto %>
</p>

<p>
  <strong>Data de Inicio:</strong>
  <%= @colaborador.dt_inicio.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>Data de Saída:</strong>
  <% if @colaborador.dt_saida %>
    <%= @colaborador.dt_saida.strftime('%d/%m/%Y') %>
  <% end %>
</p>

<%= link_to 'Editar', edit_colaborador_path(@colaborador) %> |
<%= link_to 'voltar', colaboradores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadastro de Colaboradores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Seja Bem Vindo!</h1>

<ul>
    <li><%= link_to  "Cadastro de Colaborador", colaboradores_path %></li>
</ul>

<ul>
    <li><%= link_to  "Cadastro de Cargo", cargos_path %></li>
</ul>